# Generated by Django 3.0.7 on 2020-06-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='cases',
            field=models.ManyToManyField(related_name='case_manager', to='portal.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assignments',
            field=models.ManyToManyField(related_name='students', to='portal.Assignment'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='portal.StudentProfile'),
        ),
    ]
